version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    environment:
      - CPU_CORES=${ ansible_processor_cores }
      - MEMORY=${ ansible_memtotal_mb } MB
      - DISK_SPACE=${ ansible_mounts[0].size_total | int / 1024 / 1024 } MB
    restart: unless-stopped
