version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
      - /:/host_root:ro
    environment:
      - CPUS=${CPUS}
      - MEM_LIMIT=${MEM_LIMIT}
      - DISK_SIZE=${DISK_SIZE}
