# playbook.yml
---
- hosts: localhost
  connection: local
  tasks:
    - name: Установка docker-compose
      yum:
        name: docker-compose
        state: present

    - name: Клонирование репозитория с контентом для сайта
      git:
        repo: https://github.com/nginxinc/docker-nginx
        dest: /opt/docker-nginx
        update: yes

    - name: Создание docker-compose файла
      template:
        src: docker-compose.yml.j2
        dest: /opt/docker-nginx/docker-compose.yml

    - name: Запуск docker-compose
      command: docker-compose up -d
      args:
        chdir: /opt/docker-nginx
