- name: Установка docker-compose
  command: pip install docker-compose

- name: Клонирование репозитория с контентом для сайта
  git:
    repo: https://github.com/mebelshik/test_task.git
    dest: /opt/docker-nginx
    version: main

- name: Создание docker-compose файла
  copy:
    src: /opt/docker-nginx/docker-compose.yml
    dest: /opt/docker-nginx/docker-compose.yml
    owner: your_username
    group: your_group
    mode: '0644'
