- hosts: all
  become: yes
  vars:
    CPU_CORES: "{{ ansible_processor_vcpus }}"
    MEMORY: "{{ ansible_memtotal_mb }}"
    DISK_SPACE: "{{ ansible_devices.sda.size }}"
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: /path/to/your/project
        version: main

    - name: Build and run the Docker container
      community.docker.docker_compose:
        project_src: /path/to/your/project
        build: yes
        state: present
