- hosts: localhost
  connection: local
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: /path/to/your/project
        version: main

    - name: Build and run the Docker container
      docker_compose:
        project_src: /path/to/your/project
        build: yes
        state: present
