---
- name: Clone repository and build Docker container with nginx
  hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    project_src: /path/to/your/project
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: "{{ project_src }}"
        version: main

    - name: Build and run the Docker container
      docker_compose:
        project_src: "{{ project_src }}"
        build: yes
        state: present
