- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: /path/to/your/project
        version: main

- name: Build and run the Docker container
  docker_compose:
    project_src: "{{ playbook_dir }}/path/relative/to/playbook"
    build: yes
    state: present

