---
- name: Deploy website with system info
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: "{{ ansible_env.HOME }}/test_task"
        force: yes

    - name: Get system info
      shell: |
        echo CPUS=$(nproc) > {{ ansible_env.HOME }}/test_task/.env
        echo MEM_LIMIT=$(free -m | grep Mem | awk '{print $2}')MB >> {{ ansible_env.HOME }}/test_task/.env
        echo DISK_SIZE=$(df -h | grep /usr/share/nginx/html | awk '{print $4}') >> {{ ansible_env.HOME }}/test_task/.env
      args:
        chdir: "{{ ansible_env.HOME }}/test_task"

    - name: Run docker-compose to start Nginx container
      docker_compose:
        project_src: "{{ ansible_env.HOME }}/test_task"
        env_file: "{{ ansible_env.HOME }}/test_task/.env"
        build: yes
        state: present
