tasks:
  - name: Clone the repository
    git:
      repo: 'https://github.com/mebelshik/test_task.git'
      dest: "{{ project_src }}"
      version: main

  - name: Build and run the Docker container
    docker_compose:
      project_src: "{{ project_src }}"  # Используйте project_src вместо project_path
      build: yes
      state: present
