---
- name: Deploy website with system info
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Check if nginx user exists
      command: id -u nginx
      register: nginx_user
      ignore_errors: yes

    - name: Create nginx user if it does not exist
      user:
        name: nginx
        system: yes
        create_home: no
      when: nginx_user.rc != 0

    - name: Clone the repository
      git:
        repo: 'https://github.com/mebelshik/test_task.git'
        dest: "{{ ansible_env.HOME }}/test_task"
        force: yes

    - name: Get system info
      shell: |
        echo CPUS=$(nproc) > {{ ansible_env.HOME }}/test_task/.env
        echo MEM_LIMIT=$(free -m | grep Mem | awk '{print $2}')MB >> {{ ansible_env.HOME }}/test_task/.env
        echo DISK_SIZE=$(df -h | grep /usr/share/nginx/html | awk '{print $4}') >> {{ ansible_env.HOME }}/test_task/.env
      args:
        chdir: "{{ ansible_env.HOME }}/test_task"

    - name: Ensure Nginx user has permissions to access the web root
      file:
        path: "{{ ansible_env.HOME }}/test_task"
        owner: nginx
        group: nginx
        state: directory
        recurse: yes
        mode: '0755'

    - name: Run docker-compose to start Nginx container
      docker_compose:
        project_src: "{{ ansible_env.HOME }}/test_task"
        env_file: "{{ ansible_env.HOME }}/test_task/.env"
        build: yes
        state: present
...
